### PR TITLE
hauler-docs configuration overhaul

### PR DESCRIPTION
**Pull request by zackbradys**
* Cleaned up, updated, and fixed `hauler-docs` repository
* Updated the docusaurus configuration and settings
* Added the initial layout and of hauler docs

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by zackbradys** [comment]
Screenshot 2023-11-03 at 6 35 36 PM

**Comment by zackbradys** [comment]
Screenshot 2023-11-03 at 6 35 44 PM

**Comment by zackbradys** [comment]
Screenshot 2023-11-03 at 6 50 26 PM

**Review by zackbradys — COMMENTED** [review]
LGTM! 🚀

**Comment by amartin120** [comment]
LGTM!

**Pull request merged**
